# Use the official Python image as the base
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Copy the necessary files into the container
COPY . /app

# Install necessary dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run the model training script to train and save the model during the build
RUN python train_hotspot.py

# Expose port 5000 for the Flask app
EXPOSE 5000

# Command to run the Flask app when the container starts
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "server:app"]
